---
 - name: Installing Java on RHEL and Also Debian Family Managed Nodes
   hosts: all
   gather_facts: true
   become: true
   tasks:
    - name: Installing Java on RHEL Family Managed Nodes
      ansible.builtin.yum:
        name: java
        state: present
        update_cache: true
      when: ansible_facts.os_family == "RedHat"
    - name: Installing Java on Debian Family Managed Nodes
      ansible.builtin.apt:
        name: default-jdk
        state: present
        update_cache: true
      when: ansible_facts.os_family == "Debian"
