---
# tasks file for httpd
- name: Installing package on RHEL Family 
  ansible.builtin.yum: 
    name: "{{pkgName.get(ansible_facts.os_family)}}"
    state: present
    update_cache: true 
  when: ansible_facts.os_family == "RedHat" 
- name: Installing package on Debian Family 
  ansible.builtin.apt:
    name: "{{pkgName.get(ansible_facts.os_family)}}"    
    state: present
    update_cache: true 
  when: ansible_facts.os_family == "Debian" 
- name: Copying the index.html file to /var/www/html/index.html
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.html 
  notify: Restart WebServer

