---
- name: Play for loops
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Creating a file 
      ansible.builtin.file:
        path: /tmp/"{{item}}"
        state: touch 
      loop:     
        - config
        - config.default
        - config.test      