---
- name: Play to install packages on different os families 
  hosts: dev 
  gather_facts: true 
  become: yes
  tasks: 
    # - import_tasks: install_RedHat_Pkg.yml
    #   when: ansible_facts.os_family == "RedHat" 
    # - import_tasks: install_Debian_Pkg.yml   
    #   when: ansible_facts.os_family == "Debian"   
    # It wont work -   import_tasks: install_{{ansible_facts.os_family}}_Pkg.yml
    # - include_tasks: install_RedHat_Pkg.yml
    #   when: ansible_facts.os_family == "RedHat" 
    # - include_tasks: install_Debian_Pkg.yml   
    #   when: ansible_facts.os_family == "Debian"     
    -   include_tasks: install_{{ansible_facts.os_family}}_Pkg.yml