---
- name: Play to install httpd/apache2 on different os families 
  hosts: dev 
  gather_facts: true 
  vars: 
    pkgName:  
      RedHat: httpd 
      Debian: apache2
  become: yes
  tasks:  
    - name: Installing package on RHEL Family 
      ansible.builtin.yum: 
        name: "{{pkgName.get(ansible_facts.os_family)}}"
        state: present
        update_cache: true 
      when: ansible_facts.os_family == "RedHat" 
    - name: Installing package on Debian Family 
      ansible.builtin.apt:
        name: "{{pkgName.get(ansible_facts.os_family)}}"    
        state: present
        update_cache: true 
      when: ansible_facts.os_family == "Debian" 
    - name: Copying the index.html file to /var/www/html/index.html
      template:
        src: index.j2
        dest: /var/www/html/index.html 
      notify: Restart WebServer
  handlers:
    - name: Restart WebServer
      ansible.builtin.service: 
        name: "{{pkgName.get(ansible_facts.os_family)}}"
        state: restarted
  
            