---
- name: Play to understand about error handling 
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Finding nginx version
      ansible.builtin.command:
        cmd: 'nginx -version'
      register: nginverVerOutput
      failed_when: nginverVerOutput.rc == 0

    # - name: Making playbook status as failed using fail module
    #   ansible.builtin.fail:
    #     msg: "Failing the playbook because first task has been succeeded"
    #   failed_when: nginverVerOutput.rc == 0
      
    #  failed_when: nginverVerOutput.rc == 0 
    #   ignore_errors: true 
    # - name: Finding uname info
    #   ansible.builtin.command:
    #     cmd: uname 
    #   register: unameOutput
    # - name: Displaying nginx version and uname details
    #   ansible.builtin.debug:
    #     msg: 
    #      - "nginx version : {{nginverVerOutput.stderr}}"
    #      - "uname : {{unameOutput.stdout}}"